# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='blocked_users', to='main.User'),
        ),
    ]
